const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f5f5f5",
    cardForeground: "#0a0a0a",
    surface: "#f0f0f0",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#e5e5e5",
    mutedForeground: "#737373",
    accent: "#7C3AED",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    online: "#22C55E",
    messageBubble: "#7C3AED",
    messageBubbleOther: "#f0f0f0",
    messageBubbleText: "#ffffff",
    messageBubbleTextOther: "#0a0a0a",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8B5CF6",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    surface: "#151515",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#1E1E1E",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A2A",
    mutedForeground: "#888888",
    accent: "#7C3AED",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#2A2A2A",
    input: "#1E1E1E",
    online: "#22C55E",
    messageBubble: "#7C3AED",
    messageBubbleOther: "#1E1E1E",
    messageBubbleText: "#ffffff",
    messageBubbleTextOther: "#FFFFFF",
  },
  radius: 14,
};

export default colors;
